config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  get 'sign_in', :to=> 'sessions#new', :as => :new_session
  post 'sign_in', :to=> 'sessions#create'
  delete 'sign_out', :to => 'sessions#destroy'

  use_doorkeeper

  devise_for :users, :skip => [:sessions], :controllers => {
    registrations: 'registrations',
                                       }

  # root 'campaigns#index'

  devise_scope :user do
    # root to: "users/sessions#new"
    post 'states', :to => 'registrations#states'
    post 'cities', :to => 'registrations#cities'
    post '/api/v1/verify_account', :to => 'registrations#verify_account'
    get 'user/:token/confirm', :to => 'registrations#confirm_user'
    get '/api/v1/area_of_interest', :to => 'registrations#area_of_interest'
    get '/api/v1/project_coordinators', :to => 'registrations#project_coordinators'
    get '/api/v1/access_token', :to => 'registrations#access_token'
    get 'charities_list', :to => 'registrations#charities_list'
    get '/api/v1/all_emails', to: 'registrations#all_emails'
    get '/api/v1/check_wallet', to: 'registrations#check_wallet'
    get '/api/v1/tasks', to: 'registrations#tasks'
    get '/api/v1/update_status', to: 'campaigns#update_status'
    get 'request_activation_email/:email', to: 'registrations#request_activation_email'
  end

  # get 'cryptoapis-cb-a9e3431240e85e31fade63e5d3c3826da5555d1c0d13649b33343bca104eff74.txt', :to=> 'campaigns#verify_domain'
  # post '/transaction_callback', :to=> 'campaigns#transaction_callback'

  # namespace :api, defaults: { formate: 'json' } do
  namespace :api do
    namespace :v1 do
      resources :volunteers
      resources :nft_files, only: [:show]
      resources :nfts do
        collection do
          get 'fetch_nfts'
        end
      end
      resources :videos, only: [:index, :create, :update] do
        get 'remove_video' => 'videos#remove_video', on: :member
        post 'upload_image' => 'videos#upload_image', on: :collection
      end
      resources :transactions, only: [:create]
      resources :campaigns do
        collection do
          get :user_campaigns
        end
      end
      resource :campaign_check_in_histories
      post 'volunteer_applier' => 'campaigns#volunteer_applier'
      get 'volunteer_interest/:campaign_slug/accept/:apply_slug' => 'campaigns#accept_request'
      get "campaign_completed/:id" => 'campaigns#campaign_completed'
      get "wallet_address/:id" => 'campaigns#wallet_address'
      post "volunteer_applier_paid" => 'campaigns#volunteer_applier_paid'
      resources :chatrooms
      get 'add_users' => 'chatrooms#add_users'
      delete 'remove_users' => 'chatrooms#remove_users'
      get 'chatroom_users' => 'chatrooms#chatroom_users'
      resources :messages
      post 'group_message' => 'messages#group_message'
      get 'countries' => 'coordinators#countries'
      resources :users
      post 'update_password' => 'users#update_password'
      get 'forget_password' => 'users#forget_password'
      post 'update_user' => 'users#update_user'
      get 'user_detail' => 'users#user_detail'
      get 'unread_messages' => 'users#unread_messages'
      get 'all_users_emails' => 'users#all_users_emails'
      post 'open_ai_images' => 'users#open_ai_images'
      post 'update_database' => 'users#update_database'
    end

    scope '(v:version)', format: false, defaults: { format: :json, version: 1 }, constraints: { version: /[1]/ } do
      post 'get_volunteered_projects' => 'coordinators#get_volunteered_projects'
      post 'check_in' => 'coordinators#check_in'
      post 'check_out' => 'coordinators#check_out'
      get 'volunteer/:id' => 'coordinators#select_volunteer'
      get 'goods_wallet_balance' => 'coordinators#goods_wallet_balance'

      namespace :users do
        controller :registrations do
          post :sign_up, action: :create
          get :all_emails, action: :all_emails
          get :tasks, action: :tasks
        end
        controller :sessions do
          delete :sign_out, action: :destroy
          post :sign_in, action: :create
        end
      end
      get 'get_coordinators' => 'coordinators#coordinators_list'
      post 'append_message' => 'messages#append_message'
    end
  end

  # get 'calendar' => 'events#index'
  # resources :events,      only:  [:new, :create, :show] do
  #     resources :attendees,   only:  [:new, :create]
  #     resource :download_badges_pdf, only: [:show]
  # end
  # resources :alliances, path: 'charities',   only:  [:index, :show, :edit, :update]
  # resources :vendors,   only:  [:index, :show, :edit, :update]
  # resources :churches,    only:  [:index, :show, :edit, :update]
  # resources :users,       only:  [:edit, :update]
  # resources :payments,    only:  [:new, :create]
  # resources :ads,         only:  [:new, :create, :edit, :update]
  scope :admin do
    resources :invites, only: :index
  end
  # resources :cards,       only:  [:new, :create, :edit, :update]
  # resources :need_contributions, only: [:create]
  resources :volunteer_appliers, only: [:create]
  # resources :messages, only: [:create]


  # post 'append_message' => 'messages#append_message'

  resources :messages do
    collection do
      get :get_messages
      post :create_message
    end
    
  end
  
  # resources :products do
  #   collection do
  #     get :user_products
  #   end
  #   member do
  #     delete :destroy_product_media
  #   end
  # end

  # resources :campaigns do
  #   collection do
  #     get :user_campaigns
  #     get :project_categories
  #     # get :winner
  #     # get :showing_wallet
  #     post :send_amount
  #     post :receive_amount
  #   end
  #   member do
  #     delete :destroy_campaign_media
  #     get :get_need
  #     post :create_message
  #   end
  #   resources :campaign_donations, only: [:new, :create]
  #   resources :nfts
  # end

  # resources :charitable_donations, only: [:new, :create]

  # resources :chamber_donations, only: [:new, :create]

  # resources :needs,       only: [:new, :create, :show] do
  #   resources :resources,          only: [:new, :create]
  # end

  # resources :resources,   only: [:new, :create] do
  #   get :accept, on: :member
  # end

  # resources :volunteers do
  #   member do
  #     put :get_volunteer
  #   end
  # end

  # resources :votes

  # Subscription cancel
  # get 'payments/cancel_subscription' , as: :cancel_subscription


  # campaign customized routes

  get 'coordinator/campaigns' => 'campaigns#coordinator_campaigns'

  # Temporary Hidden
  # resources :job_leads, only: [:new, :create]

  # get 'dashboard(/:user_id)' => 'users#dashboard', as: :dashboard
  # get 'rewards'=> 'home#rewards'
  # get 'currency-of-good'=> 'home#currency_of_good'
  #----------------7 Tool Box Links ------------------
  # get 'tool_boxes' => 'tool_boxes#index'
  # get 'tool_box' => 'tool_boxes#show'
  # get 'documents' => 'tool_boxes#documents'
  # get 'tool_box_resources' => 'tool_boxes#resources'
  # get 'tool_box_events' => 'tool_boxes#events'
  # volunteer management

  get 'volunteer_interest/:campaign_id' => 'campaigns#volunteer_interest'
  get 'volunteer_interest/:campain_id/accept/:volunteer_id' => 'campaigns#accept_request'
  get 'volunteer/campaigns' => 'campaigns#user_accepted_campaigns'
  post 'api/v1/volunteer' => 'volunteers#create'

  # get 'blog' => 'tool_boxes#blog', as: :blog
  #--------------------------------------------------

  # #---------------- Invite  Links ------------------
  # get "invite/new" => 'invite#new', :as => :new_invite
  # post "invite/create" => 'invite#create', :as => :invites
  # #---------------------------------------------------

  # get 'docs' => 'home#save_docs'

  # get 'contact_us' =>  'contact_form#new'
  # resources "contact_forms", only: [:new, :create]
end

app/views/users/dashboard/partials/business/_account_info.html.erb
<div class="col-xs-12 col-sm-6 chop">
  <!-- BEGIN BORDERED TABLE PORTLET-->
  <div class="portlet light portlet-fit">
    <div class="portlet-title">
      <div class="caption">
        <span class="caption-subject sbold uppercase">Your Membership</span>
      </div>
    </div>
    <div class="portlet-body">
      <div class="form-group form-md-line-input text-center" style="padding-top:0">
        <p style="margin-bottom:0; color: #52BEEF;text-align:left">Logo</p>
        <%- if @business.logo? %>
          <%= image_tag @business.logo.url, style: "max-width:80%"%>
        <% else %>
          <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="">
        <% end %>
      </div>
      <div class="form-group form-md-line-input">
          <div class="form-control form-control-static"> <%= @business.name %> </div>
          <label for="form_control_1">Name</label>
      </div>
      <div class="form-group form-md-line-input">
          <div class="form-control form-control-static"> <%= @business.contact_email %> </div>
          <label for="form_control_1">Contact Email</label>
      </div>
      <div class="form-group form-md-line-input">
          <div class="form-control form-control-static"> <%= @business.region.try(:name) %> </div>
          <label for="form_control_1">Region</label>
      </div>
      <div class="form-group form-md-line-input">
          <div class="form-control form-control-static"> <%= current_user.expiration.strftime("%m/%d/%Y") rescue '' %> </div>
          <label for="form_control_1">Membership Expiration</label>
      </div>
      <div class="form-group form-md-line-input">
        <div class="form-control form-control-static">
          <ul style="padding-left:20px">
            <li><%= @business.business_category.try(:name) %></li>
          </ul>
        </div>
        <label for="form_control_1">Categories</label>
      </div>
      <div class="row text-center"  style="padding-top:10px">
        <%= link_to 'Edit Account', edit_user_path(current_user), class:"btn btn-small active btn-blue", style:"width:100%;"%>
      </div>
      <div class="row text-center"  style="padding-top:10px">
        <%= link_to 'Edit Business', edit_business_path(@business), class:"btn btn-small active btn-blue", style:"width:100%;"%>
      </div>
      <%if current_user.subscriptions.present?%>
        <div class="row text-center"  style="padding-top:10px">
          <%= link_to 'Cancel Membership', cancel_subscription_path, class:"btn btn-small active btn-blue", style:"width:100%;"%>
        </div>
      <%else%>
        <div class="row text-center" style="padding-top:10px">
          <%= link_to 'Renew Membership', new_payment_path, class:"btn btn-small active btn-blue", style:"width:100%;"%>
        </div>
      <%end%>
      <%if @card.present?%>
        <div class="row text-center"  style="padding-top:10px">
          <%= link_to 'Update Credit Card', edit_card_path(@card), class:"btn btn-small active btn-blue", style:"width:100%;"%>
        </div>
      <%else%>
        <div class="row text-center"  style="padding-top:10px">
          <%= link_to 'Add Credit Card', new_card_path, class:"btn btn-small active btn-blue", style:"width:100%;"%>
        </div>
      <%end%>
    </div>
    <!-- END BORDERED TABLE PORTLET-->
  </div>
</div>

app/views/users/dashboard/partials/business/_ads.html.erb
<div class="col-sm-12 chop">
  <!-- BEGIN BORDERED TABLE PORTLET-->
  <div class="portlet light portlet-fit ">
      <div class="portlet-title">
          <div class="caption">
              <span class="caption-subject sbold uppercase">
                <%= @is_owner ? 'Your' : @prefix %> Ads
              </span>
          </div>
      </div>
      <div class="portlet-body">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible;">
              <table class="table table-hover table-light">
                  <thead>
                      <tr class="uppercase" >
                          <th>#</th>
                          <th> Ad </th>
                          <th> Status </th>
                          <th> Expires </th>
                          <th class="text-center"> Action </th>
                      </tr>
                  </thead>
                  <tbody>
                    <%- unless current_user.ads.exists? %>
                      <tr class="text-center">
                        <td colspan="5" >
                          <% if @is_owner %>
                              You have not yet created an Ad
                          <% else %>
                              <%= @prefix %> has not yet created an Ad
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                    <%  current_user.ads.each_with_index  do |ad, i| %>
                      <tr>
                          <td><%= i+1 %></td>
                          <td><%= image_tag ad.image.url(:thumb) %></td>
                          <td><%= ad.approval_state.slice(0,1).capitalize + ad.approval_state.slice(1..-1) %></td>
                          <% if (ad.paid? || ad.approved?) %>
                            <!-- <td><i class="fa fa-check font-green-sharp"></i> Active</td> -->
                            <td><%= ad.expiration.strftime('%-m/%-d/%y') rescue '' %></td>
                            <td class="text-center">
                              <%= link_to "Edit", edit_ad_path(ad), class: 'btn btn-sm active btn-blue' %>
                            </td>

                          <% else %>
                            <!-- <td><i class="fa fa-times font-red-mint"></i> Inactive</td> -->
                            <td></td>
                            <td class="text-center">
                              <%= link_to "Activate", edit_ad_path(ad), class: 'btn btn-sm active btn-blue' %>
                            </td>
                          <% end %>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
  <!-- END BORDERED TABLE PORTLET-->
</div>

app/views/users/dashboard/partials/business/_charity_donations.html.erb
<div class="col-sm-12 chop">
  <!-- BEGIN BORDERED TABLE PORTLET-->
  <div class="portlet light portlet-fit ">
      <div class="portlet-title">
          <div class="caption">
              <span class="caption-subject sbold uppercase">Charitable Donations</span>
          </div>
      </div>
      <div class="portlet-body">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible;">
              <table class="table table-hover table-light">
                  <thead>
                      <tr class="uppercase" >
                          <th> Date </th>
                          <th> Charity </th>
                          <th> Amount</th>

                      </tr>
                  </thead>
                  <tbody>
                    <%- unless @charitable_donations.present? %>
                      <tr class="text-center">
                        <td colspan="4" >
                          <%= @is_owner ? 'Your' : @prefix %> Members have Donated to 0 Fundraisers
                        </td>
                      </tr>
                    <% end %>
                    <%  @charitable_donations.each do |donation| %>
                      <tr>
                        <td><%= distance_of_time_in_words(Time.now, donation.created_at) %></td>
                          <td><%= donation.charity_name %></td>
                          <td><%= number_to_currency(donation.donation_amount) %></td>
                          
                      </tr>
                    <% end %>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
  <!-- END BORDERED TABLE PORTLET-->
</div>

app/views/users/dashboard/partials/business/_helpful_links.erb
<div class="col-xs-12 col-sm-6 col-sm-left chop">
  <div class="portlet light portlet-fit">
      <div class="portlet-title">
          <div class="caption">
              <span class="caption-subject sbold uppercase">Helpful Links</span>
          </div>
      </div>
      <div class="portlet-body row">
        <div class="col-xs-12 text-center">
          <!--<div class="row">-->
            <%#= link_to new_ad_path, class: "icon-btn" do %>
                <!--<i class="fa fa-id-badge"></i>-->
                <!--<div> Purchase Ad </div>-->
                <!-- <span class="badge badge-success"> 4 </span> -->
            <%# end %>
          <!--</div>-->
          <!--<hr />-->

          <div class="row">
            <%= link_to new_campaign_path, class: 'icon-btn' do %>
                <i class="fa fa-bullhorn"></i>
                <div> Submit Campaign </div>
            <% end %>
          </div>

          <div class="row">
            <%= link_to new_campaign_path, :class => "icon-btn" do %>
                <i class="fa fa-bullhorn"></i>
                <div> Submit Campaign </div>
            <% end %>
          </div>

          <div class="row">
            <%= link_to new_event_path, :class => "icon-btn" do %>
                <i class="fa fa-calendar"></i>
                <div> Submit Event </div>
                <!-- <span class="badge badge-success"> 4 </span> -->
            <% end %>
      </div>
      <hr />
      <div class="row">
      <%= link_to campaigns_path, :class => "icon-btn" do %>
          <i class="fa fa-search"></i>
          <div> Find Fundraisers </div>
      <% end %>
      </div>
      <div class="row">
      <%= link_to alliances_path, :class => "icon-btn" do %>
          <i class="fa fa-university "></i>
          <div> Find Alliances </div>
      <% end %>
      </div>
      <div class="row">
      <%= link_to churches_path, :class => "icon-btn" do %>
          <i class="fa fa-users"></i>
          <div> Find Churches </div>
      <% end %>
      </div>

      <hr>
      <div class="row">
        <%= mail_to 'support@sc-c3.org', subject: 'Prayer Request', class: 'icon-btn' do %>
            <i class="fa fa-send"></i>
            <div>Submit Prayer Request</div>
        <% end %>
      </div>
        <!-- <hr />
        <div class="row">
          <a href="javascript:;" class="icon-btn disabled">
            <i class="fa fa-external-link "></i>
            <div> Resources & Links </div>
          </a>
        </div> -->
      </div>
    </div>
    </div>
  </div>

app/views/users/dashboard/partials/business/_in_kind_donations.html.erb
<div class="col-sm-12 chop">
  <!-- BEGIN BORDERED TABLE PORTLET-->
  <div class="portlet light portlet-fit ">
      <div class="portlet-title">
          <div class="caption">
              <span class="caption-subject sbold uppercase">In-Kind Donations</span>
          </div>
      </div>
      <div class="portlet-body">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible;">
              <table class="table table-hover table-light">
                  <thead>
                      <tr class="uppercase" >
                          <th> Date </th>
                          <th> Campaign </th>
                          <th> Item </th>
                          <th class="text-center"> Actions </th>
                      </tr>
                  </thead>
                  <tbody>
                    <%- unless @inkind_donations.present? %>
                      <tr class="text-center">
                        <td colspan="4" >
                          <%= @is_owner ? 'Your' : @prefix %> Members have Donated to 0 Fundraisers
                        </td>
                      </tr>
                    <% end %>
                    <%  @inkind_donations.each do |donation| %>
                      <tr>
                        <td><%= distance_of_time_in_words(Time.now, donation.created_at) %></td>
                          <td><%= donation.campaign.name %></td>
                          <td><%= donation.title %></td>
                          <td class="text-center">
                            <div class="actions" class="text-center">
                              <div class="btn-group">
                                <%= link_to 'View', donation.campaign, class:"btn dark btn-outline btn-circle btn-sm" %>
                              </div>
                          </div>
                         </td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
  <!-- END BORDERED TABLE PORTLET-->
</div>

app/views/users/dashboard/partials/business/_your_campaigns.html.erb
<div class="col-sm-12 chop">
  <!-- BEGIN BORDERED TABLE PORTLET-->
  <div class="portlet light portlet-fit ">
      <div class="portlet-title">
          <div class="caption">
              <span class="caption-subject sbold uppercase">Campaign Donations</span>
          </div>
          <div class="actions">
             <div class="btn-group btn-group-devided">
               <%= link_to "Donate Now", campaigns_path, class: "btn btn-sm active btn-blue" %>
             </div>
         </div>

      </div>
      <div class="portlet-body">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible;">
              <table class="table table-hover table-light">
                  <thead>
                      <tr class="uppercase" >
                          <th> Date </th>
                          <th> Campaign </th>
                          <th> Amount</th>
                          <th class="text-center"> Actions </th>
                      </tr>
                  </thead>
                  <tbody>
                    <%- unless @campaign_donations.present? %>
                      <tr class="text-center">
                        <td colspan="4" >
                          <%= @is_owner ? 'Your' : @prefix %> Members have Donated to 0 Fundraisers
                        </td>
                      </tr>
                    <% end %>
                    <%  @campaign_donations.each do |donation| %>
                      <tr>
                        <td><%= distance_of_time_in_words(Time.now, donation.created_at) %></td>
                        <td><%= donation.try(:campaign).try(:name) %></td>
                        <td><%= number_to_currency(donation.donation_amount) %></td>
                        <td class="text-center">
                          <div class="actions" class="text-center">
                            <div class="btn-group">
                              <%= link_to 'View', donation.campaign, class:"btn dark btn-outline btn-circle btn-sm" %>
                            </div>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
  <!-- END BORDERED TABLE PORTLET-->
</div>

app/views/users/dashboard/partials/business/_your_members.erb
<div class="col-sm-12 chop">
  <!-- BEGIN BORDERED TABLE PORTLET-->
  <div class="portlet light portlet-fit ">
      <div class="portlet-title">
          <div class="caption">
              <span class="caption-subject sbold uppercase">
                <%= @is_owner ? 'Your' : @prefix %> Members
              </span>
          </div>
          <!-- <div class="actions">
             <div class="btn-group btn-group-devided">
               <%= link_to "Send Invite", campaigns_path, class: "btn btn-sm active btn-blue" %>
             </div>
         </div> -->

      </div>
      <div class="portlet-body">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible;">
              <table class="table table-hover table-light">
                  <thead>
                      <tr class="uppercase" >
                          <th>#</th>
                          <th> Name </th>
                          <th> Email</th>
                          <th class="text-center"> Joined </th>
                      </tr>
                  </thead>
                  <tbody>
                    <%- unless @business.users.all.present? %>
                      <tr class="text-center">
                        <td colspan="4" >
                          <% if @is_owner %>
                              Sorry you have 0 Members
                          <% else %>
                              <%= @prefix %> has 0 Members
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                    <%  @business.users.all.each_with_index  do |user, i| %>
                      <tr>
                          <td><%= i+1 %></td>
                          <td><%= user.name %></td>
                          <td><%= user.email %></td>
                          <td class="text-center"><%= distance_of_time_in_words(Time.now, user.created_at) %></td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
  <!-- END BORDERED TABLE PORTLET-->
</div>